### ISSUE TITLE
java.lang.Throwable: 读取翻译内容为空

### ISSUE THREAD

**Issue by miaoweiwei** [shuzijun/leetcode-editor#104]
`
java.lang.Throwable: 读取翻译内容为空
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.translation(QuestionManager.java:274)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.parseQuestion(QuestionManager.java:216)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:49)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:34)
	at com.shuzijun.leetcode.plugin.actions.LoginAction.perform(LoginAction.java:116)
	at com.shuzijun.leetcode.plugin.actions.AbstractAsynAction$1.run(AbstractAsynAction.java:17)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by shuzijun** [comment]
参考#101
