### ISSUE TITLE
读取翻译内容为空

### ISSUE THREAD

**Issue by 8090Lambert** [shuzijun/leetcode-editor#105]
java.lang.Throwable: 读取翻译内容为空
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.translation(QuestionManager.java:274)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.parseQuestion(QuestionManager.java:216)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:49)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:34)
	at com.shuzijun.leetcode.plugin.actions.RefreshAction.perform(RefreshAction.java:18)
	at com.shuzijun.leetcode.plugin.actions.AbstractAsynAction$1.run(AbstractAsynAction.java:17)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by shuzijun** [comment]
参考#101
