### ISSUE TITLE
Still fail to login leetcode with error "Access is allowed from event dispatch thread only"

### ISSUE THREAD

**Issue by ycchen24** [shuzijun/leetcode-editor#108]
unsign plugin with version 6.0 on mac, fail to login leetcode with all error message

env:
version:v6.0
pycharm:2019.3.1
os: mac
reproduced step:
1:uninstall leetcode plugin from pycharm and restart pycharm
2:reinstall leetcode plugin from disk [<v6.0>](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.0) and restart pycharm
4:go to leetcode plugin tool window and click sing out, to make sure it is sign out
5:go to leetcode plugin tool window and click sing in all error is generated

error message:
stacktrace.txt
```
Access is allowed from event dispatch thread only.

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@2082216a
Current thread: Thread[ApplicationImpl pooled thread 7,4,Idea Thread Group] 1823088674
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 2012576947
        at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:959)
        at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:948)
        at com.intellij.openapi.actionSystem.impl.PresentationFactory.getPresentation(PresentationFactory.java:31)
        at com.intellij.openapi.wm.impl.IdeMenuBar.expandActionGroup(IdeMenuBar.java:427)
        at com.intellij.openapi.wm.impl.IdeMenuBar.doUpdateMenuActions(IdeMenuBar.java:345)
        at com.intellij.openapi.wm.impl.IdeMenuBar.updateMenuActions(IdeMenuBar.java:337)
        at com.intellij.openapi.wm.impl.IdeMenuBar.updateMenuActions(IdeMenuBar.java:333)
        at com.intellij.openapi.wm.impl.IdeMenuBar.addNotify(IdeMenuBar.java:252)
        at java.desktop/java.awt.Container.addNotify(Container.java:2800)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
        at java.desktop/java.awt.Container.addNotify(Container.java:2800)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
        at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:733)
        at java.desktop/java.awt.Container.addNotify(Container.java:2800)
        at java.desktop/java.awt.Window.addNotify(Window.java:786)
        at java.desktop/java.awt.Frame.addNotify(Frame.java:490)
        at com.intellij.openapi.ui.FrameWrapper$MyJFrame.addNotify(FrameWrapper.java:396)
        at java.desktop/java.awt.Window.show(Window.java:1048)
        at java.desktop/java.awt.Component.show(Component.java:1734)
        at java.desktop/java.awt.Component.setVisible(Component.java:1681)
        at java.desktop/java.awt.Window.setVisible(Window.java:1031)
        at com.intellij.openapi.ui.FrameWrapper.show(FrameWrapper.java:187)
        at com.intellij.openapi.ui.FrameWrapper.show(FrameWrapper.java:110)
        at com.shuzijun.leetcode.plugin.actions.LoginAction.perform(LoginAction.java:73)
        at com.shuzijun.leetcode.plugin.actions.AbstractAsynAction$1.run(AbstractAsynAction.java:17)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
threaddump.txt
```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on java.awt.Component$AWTTreeLock@62ed1c08 owned by "ApplicationImpl pooled thread 7" Id=32
        at java.desktop@11.0.5/java.awt.Component.invalidate(Component.java:3029)
        at java.desktop@11.0.5/java.awt.Container.invalidate(Container.java:1614)
        at java.desktop@11.0.5/java.awt.Window.dispatchEventImpl(Window.java:2770)
        at java.desktop@11.0.5/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop@11.0.5/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop@11.0.5/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop@11.0.5/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base@11.0.5/java.security.AccessController.doPrivileged(Native Method)
        at java.base@11.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base@11.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop@11.0.5/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop@11.0.5/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base@11.0.5/java.security.AccessController.doPrivileged(Native Method)
        at java.base@11.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop@11.0.5/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
        at com.intellij.ide.IdeEventQueue$$Lambda$638/0x00000008007a8440.compute(Unknown Source)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
        at java.desktop@11.0.5/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop@11.0.5/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop@11.0.5/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop@11.0.5/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop@11.0.5/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop@11.0.5/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
.....
```

**Comment by shuzijun** [comment]
Try reinstalling [v6.0](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.0)

**Comment by ycchen24** [comment]
@shuzijun yes i got this issue from v6.0

**Comment by shuzijun** [comment]
> total remove plugin again and reinstall v6.0 works

Can it work properly?

**Comment by ycchen24** [comment]
yes close issue
