### ISSUE TITLE
提示提交失败class java.lang.Boolean cannot be cast to class com.alibaba.fastjson.JSONArray

### ISSUE THREAD

**Issue by itzhangyang** [shuzijun/leetcode-editor#118]
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class com.alibaba.fastjson.JSONArray (java.lang.Boolean is in module java.base of loader 'bootstrap'; com.alibaba.fastjson.JSONArray is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5b0c5eea)
	at com.alibaba.fastjson.JSONObject.getJSONArray(JSONObject.java:131)
	at com.shuzijun.leetcode.plugin.manager.CodeManager$SubmitCheckTask.run(CodeManager.java:396)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by shuzijun** [comment]
提交的题目，语言和代码可以提供下么？

**Comment by shuzijun** [comment]
安装一下这个版本[v6.2-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.2-beta)
