### ISSUE TITLE
6.1版本登录不了，提示password probably contains sensitive information

### ISSUE THREAD

**Issue by CherleX** [shuzijun/leetcode-editor#124]
java.lang.Throwable: Element component@PersistentConfig.option.Config.option.@name=password probably contains sensitive information (file: ~/.IntelliJIdea2019.1/config/options/leetcode-config.xml)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.configurationStore.JbXmlOutputter.logSensitiveInformationError(JbXmlOutputter.kt:561)
	at com.intellij.configurationStore.JbXmlOutputter.checkIsElementContainsSensitiveInformation(JbXmlOutputter.kt:523)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:262)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:250)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:341)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:280)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:250)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:341)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:280)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:250)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:341)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:280)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:250)
	at com.intellij.configurationStore.XmlDataWriter.write$intellij_platform_configurationStore_impl(XmlElementStorage.kt:274)
	at com.intellij.configurationStore.StringDataWriter.write(XmlElementStorage.kt:421)
	at com.intellij.configurationStore.DataWriter$DefaultImpls.write$default(XmlElementStorage.kt:402)
	at com.intellij.configurationStore.XmlElementStorageKt.writeTo(XmlElementStorage.kt:413)
	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.saveLocally(FileBasedStorage.kt:119)
	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession$SaveExecutor.save(XmlElementStorage.kt:166)
	at com.intellij.configurationStore.SaveExecutorKt.executeSave(SaveExecutor.kt:91)
	at com.intellij.configurationStore.SaveExecutorKt.saveSessions(SaveExecutor.kt:85)
	at com.intellij.configurationStore.SaveSessionProducerManager$save$task$1.invoke(SaveExecutor.kt:68)
	at com.intellij.configurationStore.SaveSessionProducerManager$save$task$1.invoke(SaveExecutor.kt:22)
	at com.intellij.configurationStore.SaveSessionProducerManager.save$suspendImpl(SaveExecutor.kt:78)
	at com.intellij.configurationStore.SaveSessionProducerManager.save(SaveExecutor.kt)
	at com.intellij.configurationStore.ApplicationStoreImpl$doSave$2$1.invokeSuspend(ApplicationStoreImpl.kt:40)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:123)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:45)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.configurationStore.StoreUtil$Companion.saveDocumentsAndProjectsAndApp(storeUtil.kt:79)
	at com.intellij.configurationStore.StoreUtil.saveDocumentsAndProjectsAndApp(storeUtil.kt)
	at com.intellij.openapi.options.newEditor.SettingsDialog.applyAndClose(SettingsDialog.java:176)
	at com.intellij.openapi.options.newEditor.SettingsDialog.doOKAction(SettingsDialog.java:170)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1875)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1835)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicRootPaneUI$Actions.actionPerformed(BasicRootPaneUI.java:208)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2883)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:250)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2975)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2967)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2846)
	at java.awt.Component.processEvent(Component.java:6327)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:842)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1111)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:981)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:807)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4770)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:684)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:706)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
	at com.intellij.openapi.options.newEditor.SettingsDialog.lambda$show$0(SettingsDialog.java:73)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:73)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:137)
	at com.shuzijun.leetcode.plugin.actions.ConfigAction.actionPerformed(ConfigAction.java:14)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:183)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:147)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:415)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:702)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by shuzijun** [comment]
这是一个警告不影响登陆。建议先参考https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp_ZH.md

**Comment by CherleX** [comment]
但是我这边一直都是报错。获取不了题目。
![image](https://user-images.githubusercontent.com/3784322/72401556-4bcc1500-3787-11ea-983c-3442eb36bf82.png)

**Comment by shuzijun** [comment]
右下角有个红色的叹号，点开后看是否有详细日志，如果有多个错误，可以点击左上角的箭头查看下一个

**Comment by CherleX** [comment]
![image](https://user-images.githubusercontent.com/3784322/72409722-89d63280-37a1-11ea-8cb5-85fbbcd0bfad.png)
没有详细的报错。只有这些提示。

**Comment by shuzijun** [comment]
![20200115142033](https://user-images.githubusercontent.com/27667179/72410023-57790500-37a2-11ea-9439-b0e5711b0f40.png)
箭头指的地方

**Comment by CherleX** [comment]
![image](https://user-images.githubusercontent.com/3784322/72410894-9c05a000-37a4-11ea-9eb5-2908d459abc4.png)
确实没有这个感叹号。

**Comment by shuzijun** [comment]
![20200115145412](https://user-images.githubusercontent.com/27667179/72411916-07507180-37a7-11ea-82b6-70e758ad539c.png)
在这个日志文件里搜索 "获取题目内容错误" ，可能产生加载题目失败的原因是网络错误或者请求返回的值无法解析

**Comment by shuzijun** [comment]
如果有问题可以添加描述再打开这个Issues
