### ISSUE TITLE
提交出错

### ISSUE THREAD

**Issue by itdarkwater** [shuzijun/leetcode-editor#127]
java.lang.ClassCastException: java.lang.Integer cannot be cast to com.alibaba.fastjson.JSONArray
	at com.alibaba.fastjson.JSONObject.getJSONArray(JSONObject.java:131)
	at com.shuzijun.leetcode.plugin.manager.CodeManager$SubmitCheckTask.run(CodeManager.java:396)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by itdarkwater** [comment]
//给定一个字符串，请你找出其中不含有重复字符的 最长子串 的长度。 
//
// 示例 1: 
//
// 输入: "abcabcbb"
//输出: 3 
//解释: 因为无重复字符的最长子串是 "abc"，所以其长度为 3。
// 
//
// 示例 2: 
//
// 输入: "bbbbb"
//输出: 1
//解释: 因为无重复字符的最长子串是 "b"，所以其长度为 1。
// 
//
// 示例 3: 
//
// 输入: "pwwkew"
//输出: 3
//解释: 因为无重复字符的最长子串是 "wke"，所以其长度为 3。
//     请注意，你的答案必须是 子串 的长度，"pwke" 是一个子序列，不是子串。
// 
// Related Topics 哈希表 双指针 字符串 Sliding Window

package leetcode.editor.cn;

import java.util.HashMap;
import java.util.Map;

public class LongestSubstringWithoutRepeatingCharacters {
    public static void main(String[] args) {
        Solution solution = new LongestSubstringWithoutRepeatingCharacters().new Solution();
        solution.lengthOfLongestSubstring("abcabcbb");
    }
//leetcode submit region begin(Prohibit modification and deletion)
    class Solution {
        public int lengthOfLongestSubstring(String s) {
            if (s == null) {
                return 0;
            }
            int begin = -1;
            int length = 0;
            Map<Character, Integer> charMap = new HashMap<>();
            for (int i = 0; i < s.length() - 1; i++) {
                Integer index = charMap.get(s.charAt(i));
                if (index == null || index <= begin) {
                    charMap.put(s.charAt(i), i);
                } else {
                    if (length < i - begin -1) {
                        length = i - begin -1;
                    }
                    begin = index;
                }
            }
            return length;
        }
    }
//leetcode submit region end(Prohibit modification and deletion)

}

**Comment by itdarkwater** [comment]
升级6.1版本后解决
