### ISSUE TITLE
Test/Submit the code with keyboard shortcut under edit console generated error "Can't find resource for bundle java.util.PropertyResourceBundle"

### ISSUE THREAD

**Issue by ycchen24** [shuzijun/leetcode-editor#129]
using keyboard shortcut to operate run testcase/submit the code to leetcode under editor window. IDE generate fatal error with error message

env:
version:v6.2
pycharm
os: mac
same issue on https://github.com/shuzijun/leetcode-editor/issues/102 but different error message

reproduced step:
1:set up keyboard shortcut, as cmd+' for running testcase, cmd+; for submit code
2:login to leetcode successfully
3:right-click for any program and select run test or submit code. confirm testcase run successfully and submit code completed. No problem to see successfully message on event log
4:move cursor to edit window, and using keyboard shortcut. IDE fatal error is generated

error message:
```
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key response.select
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at com.shuzijun.leetcode.plugin.utils.PropertiesUtils.getInfo(PropertiesUtils.java:15)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.getTreeQuestion(ViewManager.java:211)
	at com.shuzijun.leetcode.plugin.actions.tree.AbstractTreeAction.actionPerformed(AbstractTreeAction.java:23)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction.actionPerformed(AbstractAction.java:38)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:315)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:604)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:657)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:656)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:472)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:830)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:775)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by shuzijun** [comment]
There is no selection question when running shortcuts, this prompt problem has been fixed.
In the new version, the right-click menu on the editor has been added. It is recommended to bind shortcut keys to the operations under this menu.
