### ISSUE TITLE
连接超时。 Connect to leetcode-cn.com:443 [leetcode-cn.com/47.99.228.218] failed: Connection timed out: connect

### ISSUE THREAD

**Issue by wang-kang-kang** [shuzijun/leetcode-editor#144]
代理，证书都已经配置，但是仍然报连接超时。

错误信息（无法截图）：
 Connect to leetcode-cn.com:443 [leetcode-cn.com/47.99.228.218] failed: Connection timed out: connect

麻烦关注一下呢。

**Comment by w00416770** [comment]
使用作者建议的方式验证过代理，代理配置正常，可以访问到力扣网页。
怀疑连接的时候没使用代理连接。

**Comment by w00416770** [comment]
可能是我司的防火墙导致的

**Comment by w00416770** [comment]
排查发现插件使用的代理是windows机器的代理配置，而不是idea配置的代理配置。作者能否关注一下呢。

**Comment by shuzijun** [comment]
[v6.4-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4-beta) 这个版本修改了代理方式，试一下看是否生效

**Comment by w00416770** [comment]
试了，还是不行。
报错了。
java.lang.Throwable: 407
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:148)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:84)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:54)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:38)
	at com.shuzijun.leetcode.plugin.actions.toolbar.RefreshAction.perform(RefreshAction.java:20)
	at com.shuzijun.leetcode.plugin.actions.AbstractAsynAction$1.run(AbstractAsynAction.java:17)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by shuzijun** [comment]
代理是否是有用户名和密码? 407是网络请求返回的状态

**Comment by wang-kang-kang** [comment]
使用作者在另外一个issue给出的检测方法 GET https://www.leetcode-cn.com 获取的响应结果就是407。
这和我直接在windows上powershell中执行curl命令结果相同。
但是我的idea已经正常配置代理，可以正常下载插件。
所以还是怀疑：插件使用的代理是windows机器的代理配置，而不是idea配置的代理配置？

**Comment by shuzijun** [comment]
等我找一套环境试试

**Comment by shuzijun** [comment]
新的beta版本已更新,下载链接[v6.4-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4-beta),这个版本的网络请求与IDE保持一致，代理与IDE保持一致，设置方法与检测参考[settings-http-proxy](https://www.jetbrains.com/help/idea/settings-http-proxy.html).
