### ISSUE TITLE
v6.4登陆失败

### ISSUE THREAD

**Issue by JathonKatu** [shuzijun/leetcode-editor#176]
v6.4登陆失败,不知道为什么登录一直失败，用username也不行email也不行，telephone也不行

**Comment by shuzijun** [comment]
登陆方式参考:https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp_ZH.md  
注意区分leetcode.com与leetcode-cn.com,中文站可以使用用户名密码登陆，英文站只能使用cookie登陆

**Comment by Leonhardt92** [comment]
已尝试, 改问题还是存在, 请问如何提供 debug 日志?

**Comment by shuzijun** [comment]
@Leonhardt92 描述下登录的网址及登录的方式，如果有过程的截图更好。一般如果有错误会在右下角红色感叹号提示

**Comment by Leonhardt92** [comment]
> @Leonhardt92 描述下登录的网址及登录的方式，如果有过程的截图更好。一般如果有错误会在右下角红色感叹号提示

![Snipaste_2020-05-28_22-32-59.png](http://ww1.sinaimg.cn/large/883651a1gy1gf8jg02lx9j20jw0aojse.jpg)

![Snipaste_2020-05-28_22-33-11.png](http://ww1.sinaimg.cn/large/883651a1gy1gf8jgawq9jj20gc0est9i.jpg)

**Comment by shuzijun** [comment]
@Leonhardt92 通过Help -> Show Log in Explorer 查看日志，检查是否有 Request question list failed 关键词

**Comment by KickEGG** [comment]
碰到了相同的问题 一直无法登陆
`2020-06-01 19:59:32,913 [34715970]  ERROR -  #com.shuzijun.leetcode.plugin - HttpRequestUtils request error: 
javax.net.ssl.SSLException: SSL error probably caused by disabled SNI
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.openConnection(HttpRequests.java:617)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$300(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:154)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:137)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.process(HttpRequests.java:505)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executeGet(HttpRequestUtils.java:31)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:30)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching leetcode-cn.com found.
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:641)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.openConnection(HttpRequests.java:614)
	... 26 more
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching leetcode-cn.com found.
	at java.base/sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:207)
	at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:98)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:429)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1544)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1511)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625)
	... 43 more`

**Comment by KickEGG** [comment]
使用6.3 zip包可以正常使用

**Comment by shuzijun** [comment]
@KickEGG 由于6.4版本更换了http请求的实现.可以通过以下步骤进行确认  
1. 打开 File | Settings | Appearance & Behavior | System Settings | HTTP Proxy  
   打开 Check connection  输入 https://leetcode.com/problemset/all/ 检查是否可以正常访问
2. 参考https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004275380-Marketplace-Plugins-are-not-loaded  
   检查 Help -> Edit custom VM options 中是否存在-Djsse.enableSNIExtension=false，如存在删除后重启,再次尝试

**Comment by KickEGG** [comment]
> @KickEGG 由于6.4版本更换了http请求的实现.可以通过以下步骤进行确认
> 
> 1. 打开 File | Settings | Appearance & Behavior | System Settings | HTTP Proxy
>    打开 Check connection  输入 https://leetcode.com/problemset/all/ 检查是否可以正常访问
> 2. 参考https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004275380-Marketplace-Plugins-are-not-loaded
>    检查 Help -> Edit custom VM options 中是否存在-Djsse.enableSNIExtension=false，如存在删除后重启,再次尝试

谢谢，问题已解决；只是需要先移除了idea中vm配置参数中的 -Djsse.enableSNIExtension=false 条目。

**Comment by LjyYano** [comment]
问下我是6.4版本，idea中并没 vm配置参数中的 -Djsse.enableSNIExtension=false 条目。 Check connection 输入 https://leetcode.com/problemset/all/  能正常访问，有解决办法？

**Comment by shuomei** [comment]
> 问下我是6.4版本，idea中并没 vm配置参数中的 -Djsse.enableSNIExtension=false 条目。 Check connection 输入 https://leetcode.com/problemset/all/ 能正常访问，有解决办法？

看这里，用cookie登录就好了[https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp_ZH.md](url)

**Comment by StrandingHeart** [comment]
> > 问下我是6.4版本，idea中并没 vm配置参数中的 -Djsse.enableSNIExtension=false 条目。 Check connection 输入 https://leetcode.com/problemset/all/ 能正常访问，有解决办法？
> 
> 看这里，用cookie登录就好了[https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp_ZH.md](url)

我是2019.3版本的idea用 6.9版本的插件   使用cookie登录不上。。

**Comment by CLientLove** [comment]
> > > 问下我是6.4版本，idea中并没 vm配置参数中的 -Djsse.enableSNIExtension=false 条目。 Check connection 输入 https://leetcode.com/problemset/all/ 能正常访问，有解决办法？
> > 
> > 
> > 看这里，用cookie登录就好了[https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp_ZH.md](url)
> 
> 我是2019.3版本的idea用 6.9版本的插件 使用cookie登录不上。。

问题解决了嘛
