### ISSUE TITLE
登录提示warning: 请求失败；加载题目提示error: 加载题目失败

### ISSUE THREAD

**Issue by jesse1993** [shuzijun/leetcode-editor#197]
操作提示如下
17:23	warning: 请求失败   ---**登录操作的提示**

17:28	warning: 请求题目出错,将加载本地缓存   ---**加载题目的提示**

17:28	error: 加载题目失败

```
2020-06-28 17:28:06,301 [ 755977]  ERROR -  #com.shuzijun.leetcode.plugin - HttpRequestUtils request error: 
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:159)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2041)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1145)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.openConnection(HttpRequests.java:614)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$300(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:154)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:137)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.process(HttpRequests.java:505)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executeGet(HttpRequestUtils.java:31)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:39)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:38)
	at com.shuzijun.leetcode.plugin.actions.toolbar.RefreshAction.actionPerformed(RefreshAction.java:20)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-06-28 17:28:06,309 [ 755985]  ERROR -  #com.shuzijun.leetcode.plugin - IntelliJ IDEA 2019.3  Build #IU-193.5233.102 
2020-06-28 17:28:06,309 [ 755985]  ERROR -  #com.shuzijun.leetcode.plugin - JDK: 1.8.0_251; VM: Java HotSpot(TM) 64-Bit Server VM; Vendor: Oracle Corporation 
2020-06-28 17:28:06,309 [ 755985]  ERROR -  #com.shuzijun.leetcode.plugin - OS: Windows 10 
2020-06-28 17:28:06,317 [ 755993]  ERROR -  #com.shuzijun.leetcode.plugin - Plugin to blame: leetcode editor version: 6.4 
2020-06-28 17:28:06,317 [ 755993]  ERROR -  #com.shuzijun.leetcode.plugin - Last Action: leetcode.RefreshAction 
2020-06-28 17:28:06,317 [ 755993]  ERROR -  #com.shuzijun.leetcode.plugin - -1 
java.lang.Throwable: -1
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:148)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:74)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:47)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:38)
	at com.shuzijun.leetcode.plugin.actions.toolbar.RefreshAction.actionPerformed(RefreshAction.java:20)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by shuzijun** [comment]
1. 打开 File | Settings | Appearance & Behavior | System Settings | HTTP Proxy  
   打开 Check connection  输入 https://leetcode.com/problemset/all/ 检查是否可以正常访问
2. 参考https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004275380-Marketplace-Plugins-are-not-loaded  
   检查 Help -> Edit custom VM options 中是否存在-Djsse.enableSNIExtension=false，如存在删除后重启,再次尝试

**Comment by jesse1993** [comment]
@shuzijun 感谢你百忙中抽空回答我的问题。我按你的建议做了，结果如下
1. check connection 弹出框提示：problem with connection：Received fatal alert: handshake_failure
2.  custom VM options中不存在-Djsse.enableSNIExtension=false。
以下是我的custom VM options的全部内容：
```
-Xms4096m
-Xmx4096m
-XX:ReservedCodeCacheSize=1024m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-ea
-XX:CICompilerCount=2
-Dsun.io.useCanonPrefixCache=false
-Djava.net.preferIPv4Stack=true
-Djdk.http.auth.tunneling.disabledSchemes=""
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-Djdk.attach.allowAttachSelf=true
-Dkotlinx.coroutines.debug=off
-Djdk.module.illegalAccess.silent=true
-javaagent:D:\JetBrains\IntelliJ IDEA 2019.3\jetbrains-agent.jar
-XX:MaxInlineLevel=3
```

期待你的回复

**Comment by shuzijun** [comment]
麻烦提供下 Help -> About 中 Runtime version 和 VM 的信息。

**Comment by jesse1993** [comment]
```
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Licensed to https://zhile.io
You have a perpetual fallback license for this version
Subscription is active until July 8, 2089
Runtime version: 1.8.0_251-b08 amd64
VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4062M
Cores: 4
Registry: debugger.watches.in.variables=false, debugger.showTypes=false
Non-Bundled Plugins: BashSupport, Batch Scripts Support, CMD Support, IdeaVIM, JRebelPlugin, Key Promoter X, Lombook Plugin, QAPlug, SequenceDiagram, cn.wuzhizhan.plugin.mybatis, cn.yiiguxing.plugin.translate, com.alibaba.p3c.smartfox, com.bruce.intellijplugin.generatesetter, com.deadlock.scsyntax, com.github.tinselspoon.intellij.kubernetes, com.intellij.lang.jsgraphql, com.intellij.plugins.html.instantEditing, com.zhaow.restful.toolkit, de.kontext_e.idea.plugins.autofill, de.netnexus.camelcaseplugin, google-java-format, io.codearte.props2yaml, izhangzhihao.rainbow.brackets, jclasslib, jr-mp-ide-idea, leetcode-editor, me.serce.solidity, org.axonframework.intellij.axonplugin, org.jetbrains.plugins.vagrant
```

**Comment by shuzijun** [comment]
我使用了相同的环境，但是没办法复现这个错误，目前已知可能造成这个错误的原因有JDK版本问题、证书问题、代理问题。  
看运行环境是使用的jdk1.8，建议换成自带的JetBrains Runtime，切换方法参考[switching-boot-jdk](https://www.jetbrains.com/help/idea/switching-boot-jdk.html)

**Comment by FrCage** [comment]
我也出现了同样的错误

**Comment by shuzijun** [comment]
> 我也出现了同样的错误

查看下 Help -> About 中 Runtime version 和 VM 的信息。
如果VM信息不是JetBrains提供的JBR,例如:
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
建议换成自带的JetBrains Runtime，切换方法参考[switching-boot-jdk](https://www.jetbrains.com/help/idea/switching-boot-jdk.html)

**Comment by FrCage** [comment]
我之前通过choose runtime改成了jdk8版本，现在改回默认后解决了此问题

**Comment by ChengChuanxin94** [comment]
## 加载题目失败
```java
HttpRequestUtils request error:

javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1588)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.openConnection(HttpRequests.java:614)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$300(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:154)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:137)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.process(HttpRequests.java:505)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executeGet(HttpRequestUtils.java:31)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.isLogin(HttpRequestUtils.java:83)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:39)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:481)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
	... 39 more
```
-  `https://leetcode.com/problemset/all/` 可以正常访问  
-  vmoptions 中不存在 -Djsse.enableSNIExtension=false的配置
