### ISSUE TITLE
一直报NPE

### ISSUE THREAD

**Issue by darkaquarius** [shuzijun/leetcode-editor#21]
大佬，我idea一直报NPE

提交出错

java.lang.NullPointerException
	at com.shuzijun.leetcode.plugin.manager.CodeManager$RunCodeCheckTask.run(CodeManager.java:373)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by shuzijun** [comment]
@darkaquarius  可以提供一下题目和对应的源码么？

**Comment by darkaquarius** [comment]
大佬，有的时候重启就好了，不是某道题目的问题，一旦出现错误，所有的题目都会报这个错，重启有概率会好

**Comment by shuzijun** [comment]
增加了一些日志来定位这个问题，如果再次复现问题，可以将详细日志贴出来。  [v4.2](https://github.com/shuzijun/leetcode-editor/blob/dev/doc/leetcode-editor-V4.2.zip)

**Comment by shuzijun** [comment]
如果有问题可以添加描述再打开这个Issues
