### ISSUE TITLE
clion无法打开题目

### ISSUE THREAD

**Issue by zrzxj** [shuzijun/leetcode-editor#221]
登陆成功后。双击打开题目报错
`java.lang.RuntimeException: java.lang.AssertionError
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:680)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:685)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.openFileEditorAndSaveState(FileUtils.java:264)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.openCode(CodeManager.java:44)
	at com.shuzijun.leetcode.plugin.listener.TreeMouseListener$1.run(TreeMouseListener.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError
	at com.intellij.util.io.Page.<init>(Page.java:67)
	at com.intellij.util.io.PagePool.hitQueues(PagePool.java:135)
	at com.intellij.util.io.PagePool.alloc(PagePool.java:102)
	at com.intellij.util.io.RandomAccessDataFile.get(RandomAccessDataFile.java:95)
	at com.intellij.util.io.RandomAccessDataFile.getInt(RandomAccessDataFile.java:117)
	at com.intellij.openapi.vfs.newvfs.persistent.CompactRecordsTable.getSize(CompactRecordsTable.java:112)
	at com.intellij.util.io.storage.AbstractRecordsTable.scanForFreeRecords(AbstractRecordsTable.java:151)
	at com.intellij.util.io.storage.AbstractRecordsTable.ensureFreeRecordsScanned(AbstractRecordsTable.java:144)
	at com.intellij.util.io.storage.AbstractRecordsTable.deleteRecord(AbstractRecordsTable.java:196)
	at com.intellij.openapi.vfs.newvfs.persistent.CompactRecordsTable.deleteRecord(CompactRecordsTable.java:191)
	at com.intellij.util.io.storage.AbstractStorage.doDeleteRecord(AbstractStorage.java:321)
	at com.intellij.util.io.storage.Storage.deleteRecord(Storage.java:54)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.deleteContentAndAttributes(FSRecords.java:666)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.lambda$createRecord$2(FSRecords.java:577)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeAndHandleErrors(FSRecords.java:949)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.createRecord(FSRecords.java:564)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.makeChildRecord(PersistentFSImpl.java:1222)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.applyCreations(PersistentFSImpl.java:972)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.lambda$groupCreations$1(PersistentFSImpl.java:818)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:901)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEventsInWriteAction(RefreshSessionImpl.java:199)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:92)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:186)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.execute(RefreshQueueImpl.java:56)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.launch(RefreshSessionImpl.java:116)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.processSingleEvent(RefreshQueueImpl.java:127)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.createAndFindChildWithEventFire(VirtualDirectoryImpl.java:272)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:84)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.refreshAndFindChild(VirtualDirectoryImpl.java:279)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.refreshAndFindFileByPath(VfsImplUtil.java:117)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.refreshAndFindFileByPath(LocalFileSystemBase.java:57)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.refreshAndFindFileByIoFile(LocalFileSystemBase.java:212)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.lambda$openFileEditorAndSaveState$2(FileUtils.java:265)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by zrzxj** [comment]
open question报错
open content报错
open Solutions可以打开。但show detail报错

**Comment by shuzijun** [comment]
clion的版本是多少？
