### ISSUE TITLE
Submissions "failed to parse"

### ISSUE THREAD

**Issue by KnulpOu** [shuzijun/leetcode-editor#237]
Version: 6.6
URL: leetcode-cn.com
Submissions -> Show detail -> get "Failed to parse" error
Maybe it's because of the recent update of leetcode-cn.com submission result page?

stacktrace:
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.shuzijun.leetcode.plugin.manager.SubmissionManager.openSubmission(SubmissionManager.java:89)
	at com.shuzijun.leetcode.plugin.actions.tree.SubmissionsAction.actionPerformed(SubmissionsAction.java:37)
	at com.shuzijun.leetcode.plugin.actions.tree.AbstractTreeAction.actionPerformed(AbstractTreeAction.java:28)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by EdenChan** [comment]
这个问题我这边也出现了，点击 submissions 就报解析失败

**Comment by pisceslj** [comment]
me too!!!

**Comment by shuzijun** [comment]
leetcode-cn view submission details, request has been changed.

**Comment by iamyong** [comment]
求教大佬，后续会更新解决这个问题么？

**Comment by shuzijun** [comment]
> 求教大佬，后续会更新解决这个问题么？

这两天有时间修改一下

**Comment by wlflying1991** [comment]
计划什么时候发版啊？ 辛苦更新一下idea插件版本

**Comment by shuzijun** [comment]
@wlflying1991 [v6.8](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.8) 已经发布,可以下载zip安装，插件中心的需要经过审核，会延迟几天

**Comment by wlflying1991** [comment]
> @wlflying1991 [v6.8](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.8) 已经发布,可以下载zip安装，插件中心的需要经过审核，会延迟几天
感谢感谢
