### ISSUE TITLE
可以正常登录，但提交或运行代码时报错

### ISSUE THREAD

**Issue by karimb9** [shuzijun/leetcode-editor#247]
IDEA2020.2.1
leetcode editor6.7
错误如下：

HttpRequestUtils request error:

javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1576)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:974)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:160)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:137)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.process(HttpRequests.java:505)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executePost(HttpRequestUtils.java:46)
	at com.shuzijun.leetcode.plugin.window.LoginFrame$httpLogin$1.run(LoginFrame.java:312)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.net.SocketException: Connection reset by peer: socket write error
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
		... 32 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:958)
	... 28 more

**Comment by shuzijun** [comment]
可以先参考#197

**Comment by karimb9** [comment]
> 可以先参考#197
检查了如下两步
check connection连接正常
custom VM options中不存在-Djsse.enableSNIExtension=false。

VM是系统自带的
![image](https://user-images.githubusercontent.com/44717477/92876356-96984c80-f43c-11ea-9540-7620ceb2cc17.png)

问题依然存在

**Comment by TianYongwei** [comment]
@karimb9 升级6.8试下呢
