### ISSUE TITLE
清除了一次cache后无法run code或者submit

### ISSUE THREAD

**Issue by LoneRangerrr** [shuzijun/leetcode-editor#252]
**Describe the bug**
清除了一次cache后无法run code或者submit，没有反映，IDE会报一个错，具体错误如下

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.getClearCommentFileBody(FileUtils.java:143)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.getCodeText(CodeManager.java:228)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.RunCodeCode(CodeManager.java:173)
	at com.shuzijun.leetcode.plugin.actions.tree.RunCodeAction.actionPerformed(RunCodeAction.java:16)
	at com.shuzijun.leetcode.plugin.actions.tree.AbstractTreeAction.actionPerformed(AbstractTreeAction.java:28)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

希望大佬看下怎么解决

**Comment by shuzijun** [comment]
更新到最新版后再试试。如果还有问题，贴一下提交的代码

**Comment by LoneRangerrr** [comment]
> 更新到最新版后再试试。如果还有问题，贴一下提交的代码
可以了，卸载重新装了6.8解决了，谢谢大佬
