### ISSUE TITLE
邮箱严重问题导致拉取文件失败

### ISSUE THREAD

**Issue by NotCoderJack** [shuzijun/leetcode-editor#269]
您尚未验证自己的帐户
在验证电子邮件之前，您无法将代码提交给评判系统。
您可以在个人资料页面中重新发送验证电子邮件或更改电子邮件。

调用栈信息：
```
保存文件错误

java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1026)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.saveFile(FileUtils.java:45)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.saveFile(FileUtils.java:36)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.translation(QuestionManager.java:285)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.parseQuestion(QuestionManager.java:241)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:41)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:43)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:39)
	at com.shuzijun.leetcode.plugin.window.HttpLogin.ajaxLogin(HttpLogin.java:65)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:63)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

经验证，在web端可以正常登陆，且可以正常提交.

**Comment by NotCoderJack** [comment]
且我并未使用邮箱注册也未绑定邮箱，一直用手机号登录的。

**Comment by shuzijun** [comment]
目前是为了防止提交时报错，增加了这个验证，后续增加对手机号的验证

**Comment by DMLayMan** [comment]
我也遇到了这个类似的问题，只不过我没有任何的提示信息。
另外，我的登录状态是ok的。

**Comment by zhang377** [comment]
大佬   这个怎么解决啊

**Comment by 1813932938** [comment]
所以怎么解决啊？

**Comment by zhang377** [comment]
> 
我是用邮箱重新注册了一下账号  然后用这个账号登录就没问题了   一开始是用手机号注册的力扣号   就会报错

**Comment by 1813932938** [comment]
好的谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shuzijun/leetcode-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shuzijun/leetcode-editor] 邮箱验证问题导致拉取文件失败 (#269)





   
我是用邮箱重新注册了一下账号  然后用这个账号登录就没问题了   一开始是用手机号注册的力扣号   就会报错
