### ISSUE TITLE
plugin doesn't work at M1 chip Mac Pro

### ISSUE THREAD

**Issue by wwwkill2** [shuzijun/leetcode-editor#287]
Error:
ccess is allowed from event dispatch thread with IW lock only.

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@4a53209d
Current thread: Thread[ApplicationImpl pooled thread 44,4,Idea Thread Group] 701920212
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1916634360
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1048)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1023)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:157)
	at com.shuzijun.leetcode.plugin.window.WindowFactory.getDataContext(WindowFactory.java:37)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:25)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:972)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:663)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by shuzijun** [comment]
:sweat_smile:  no equipment to reproduce this problem

**Comment by wwwkill2** [comment]
Maybe the problem is the version of Intellij Idea, my idea version is #IU-211.5538.20, and plugin works on Android Studio, whose version is #AI-202.7660.26.42.7094744.

**Comment by wwwkill2** [comment]
This problem has been solved by the 6.5 version plugin.
