### ISSUE TITLE
通过download zip手动安装后，在Pycharm上无法运行

### ISSUE THREAD

**Issue by WhenU030** [shuzijun/leetcode-editor#31]
环境：

> PyCharm 2019.1.3 (Professional Edition)
> Build #PY-191.7479.30, built on May 29, 2019
> JRE: 11.0.2+9-b159.60 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.14.5

-------------------------------------------------------------------
1. 只有`idea-leetcode-plugin.jar` 可以添加成功

当添加 `jsoup-1.11.3.jar` 和 `fastjson-1.2.47.jar`时， 跳出`Fail to load plugin descriptor from file jsoup-1.11.3.jar/fastjson-1.2.47.jar`

2. 在LoginName和Password全都正确的情况下，Login 提示` info: login failed, examine e-mail or password
`

3. Refresh， 出现IDE Fatal Errors
```
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSONObject
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.parseQuestion(QuestionManager.java:196)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:51)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:34)
	at com.shuzijun.leetcode.plugin.actions.RefreshAction.perform(RefreshAction.java:18)
	at com.shuzijun.leetcode.plugin.actions.AbstractAsynAction$1.run(AbstractAsynAction.java:17)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source
```

**Comment by WhenU030** [comment]
不过如果直接通过plug-in library安装就完全没有问题

**Comment by shuzijun** [comment]
1，3：安装那个压缩包不需要解压，直接安装就可以
2：确认一下账号和网站是否对应，建议先通过网页版登陆确认一下，再尝试先点击退出按钮，再登陆

**Comment by WhenU030** [comment]
solved. 谢谢

**Comment by lucas1993ch** [comment]
> 1，3：安装那个压缩包不需要解压，直接安装就可以
> 2：确认一下账号和网站是否对应，建议先通过网页版登陆确认一下，再尝试先点击退出按钮，再登陆

把这个加入到ReadMe.md中会提高用户首次安装leetcode-plugin的成功率。
