### ISSUE TITLE
Mac环境打开题目时IDEA报错

### ISSUE THREAD

**Issue by StefanOrmsby** [shuzijun/leetcode-editor#316]
保存文件错误

java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1024)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.saveFile(FileUtils.java:45)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.saveFile(FileUtils.java:36)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.translation(QuestionManager.java:285)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.parseQuestion(QuestionManager.java:241)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:41)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:43)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:39)
	at com.shuzijun.leetcode.plugin.window.HttpLogin.ajaxLogin(HttpLogin.java:66)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:63)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by shuzijun** [comment]
参考#313

**Comment by StefanOrmsby** [comment]
> 参考#313

感谢大佬，问题已解决
