### ISSUE TITLE
获取题目报错 java.io.IOException: No such file or directory

### ISSUE THREAD

**Issue by sjx782392329** [shuzijun/leetcode-editor#318]
获取题目的时候报错

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: net.sf.opk.avro-schema-support (203.0.0), org.antlr.intellij.plugin (1.16), com.aegamesi.java_visualizer.plugin (2.2.0), com.yiycf.plugins.mavenDependencyHelper (2.1), edu.berkeley.cs61b.plugin (2.0.2), MavenRunHelper (4.12.203.000.0), org.jetbrains.kotlin (211-1.4.32-release-IJ6693.72), org.intellij.scala (2021.1.16), leetcode-editor (6.9)
Kotlin: 211-1.4.32-release-IJ6693.72
```
java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1026)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.saveFile(FileUtils.java:45)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.openContent(CodeManager.java:76)
	at com.shuzijun.leetcode.plugin.actions.tree.OpenContentAction.actionPerformed(OpenContentAction.java:19)
	at com.shuzijun.leetcode.plugin.actions.tree.AbstractTreeAction.actionPerformed(AbstractTreeAction.java:28)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by shuzijun** [comment]
参考#313

**Comment by sjx782392329** [comment]
多谢，问题已经解决了
