### ISSUE TITLE
sign in的时候提示请求失败

### ISSUE THREAD

**Issue by ryancat2011** [shuzijun/leetcode-editor#341]
![image](https://user-images.githubusercontent.com/67581470/121984463-952df300-cdc5-11eb-92ba-6c32102a9765.png)

HttpRequestUtils request error:

java.net.SocketException: Permission denied: connect
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.openConnection(HttpRequests.java:614)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$300(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:154)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:137)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.process(HttpRequests.java:505)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executeGet(HttpRequestUtils.java:31)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:29)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by alexgoing1** [comment]
可以试试[LeetCode Assistant](https://plugins.jetbrains.com/plugin/16770-leetcode-assistant/documentation), 免费使用。
