### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by EngineKing** [shuzijun/leetcode-editor#347]
v6.9登录失败，使用HTTP proxy输入https://leetcode-cn.com/，不能访问，检查vm options中没有-D的那个参数

**Comment by shuzijun** [comment]
检查代理是否正常，以及提供下网络连接的报错内容

**Comment by EngineKing** [comment]
使用check connection连接https://leetcode-cn.com/    会报错（在浏览器中访问此地址是没有问题的），报错如下：
![image](https://user-images.githubusercontent.com/43648071/123626274-3e073400-d843-11eb-9b8f-37d62b543741.png)

**Comment by EngineKing** [comment]
插件的完整报错信息：
HttpRequestUtils request error:

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2038)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.openConnection(HttpRequests.java:614)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$300(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:154)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:137)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.process(HttpRequests.java:505)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executeGet(HttpRequestUtils.java:31)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:29)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by shuzijun** [comment]
参考#197，检查 Help -> About 中 Runtime version 和 VM 的信息。
