### ISSUE TITLE
异常复现征集

### ISSUE THREAD

**Issue by shuzijun** [shuzijun/leetcode-editor#371]
看到很多提交的异常，但是无法复现问题。
如果遇到以下异常，可以提供下详细的操作步骤及遇到的场景，如与题目相关提供下题目编号。

**Comment by shuzijun** [comment]
```
java.lang.NullPointerException: null
    at com.shuzijun.leetcode.plugin.actions.toolbar.SortAction.update(SortAction.java:42)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:130)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:144)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:573)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$7(ActionUpdater.java:129)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$9(ActionUpdater.java:182)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
```

**Comment by shuzijun** [comment]
```
java.lang.NullPointerException: null
    at com.shuzijun.leetcode.plugin.window.HttpLogin.ajaxLogin(HttpLogin.java:86)
    at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:63)
    at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
```

**Comment by shuzijun** [comment]
```
java.lang.NoClassDefFoundError: Could not initialize class com.shuzijun.leetcode.plugin.editor.LCVPanel
    at com.shuzijun.leetcode.plugin.editor.LCVPreview.<init>(LCVPreview.java:68)
    at com.shuzijun.leetcode.plugin.editor.LCVProvider.createEditor(LCVProvider.java:27)
    at com.shuzijun.leetcode.plugin.editor.SplitTextEditorProvider$2.build(SplitTextEditorProvider.java:134)
    at com.shuzijun.leetcode.plugin.editor.QuestionEditorProvider$1.build(QuestionEditorProvider.java:50)
```

**Comment by shuzijun** [comment]
```
java.lang.NullPointerException: null
    at com.shuzijun.leetcode.plugin.actions.toolbar.FindActionGroup.update(FindActionGroup.java:43)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:130)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:144)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:573)
```

**Comment by shuzijun** [comment]
```
java.lang.NullPointerException: null
    at com.shuzijun.leetcode.plugin.utils.CommentUtils.createComment(CommentUtils.java:19)
    at com.shuzijun.leetcode.plugin.manager.CodeManager.openCode(CodeManager.java:50)
    at com.shuzijun.leetcode.plugin.actions.tree.OpenAction.actionPerformed(OpenAction.java:18)
    at com.shuzijun.leetcode.plugin.actions.tree.AbstractTreeAction.actionPerformed(AbstractTreeAction.java:28)
    at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
```

**Comment by dmc-forwardtogether** [comment]
**有md，但是java文件无法打开，每题都是这样**
java.lang.ExceptionInInitializerError
	at com.shuzijun.leetcode.plugin.editor.LCVPreview.<init>(LCVPreview.java:68)
	at com.shuzijun.leetcode.plugin.editor.LCVProvider.createEditor(LCVProvider.java:27)
	at com.shuzijun.leetcode.plugin.editor.SplitTextEditorProvider$2.build(SplitTextEditorProvider.java:134)
	at com.shuzijun.leetcode.plugin.editor.QuestionEditorProvider$1.build(QuestionEditorProvider.java:50)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:997)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:969)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1786)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:968)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:456)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:965)
	at com.jetbrains.rdserver.editors.BackendServerFileEditorManager.openFileImpl4(BackendServerFileEditorManager.kt:63)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$14(FileEditorManagerImpl.java:891)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:890)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:764)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:731)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openEditorImpl$22(FileEditorManagerImpl.java:1269)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorManagerImpl.java:1263)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileEditor(FileEditorManagerImpl.java:1239)
	at com.intellij.openapi.fileEditor.FileEditorManager.openEditor(FileEditorManager.java:222)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInAnyFileEditor(FileNavigatorImpl.java:81)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditor(FileNavigatorImpl.java:62)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditorOrNativeApp(FileNavigatorImpl.java:47)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigate(FileNavigatorImpl.java:30)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:91)
	at com.intellij.psi.impl.PsiElementBase.navigate(PsiElementBase.java:196)
	at com.intellij.codeInsight.navigation.NavigationUtil.lambda$openFileWithPsiElement$2(NavigationUtil.java:177)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:170)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:263)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:273)
	at com.intellij.util.OpenSourceUtil.navigateToSource(OpenSourceUtil.java:119)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:74)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:58)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:51)
	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:19)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:172)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:166)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:394)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:44)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:237)
	at com.intellij.ui.jcef.JCEFHtmlPanel.<clinit>(JCEFHtmlPanel.java:17)
	... 95 more

**Comment by shuzijun** [comment]
@dmc-forwardtogether 提供下*Help* -> *About*里的信息

**Comment by dmc-forwardtogether** [comment]
@shuzijun 
IntelliJ IDEA 2021.2 (Ultimate Edition)
内部版本号 #IU-212.4746.92，July 27, 2021 构建
Licensed to 
订阅有效期至 January 18, 2022。
For educational use only.
运行时版本: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1300M
Cores: 8
Registry: ide.browser.jcef.enabled=false, javaee.legacy.project.wizard=true
Non-Bundled Plugins: com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.11.1), com.intellij.zh (212.231), leetcode-editor (7.0), com.alibaba.p3c.smartfox (2.1.1), org.jetbrains.plugins.vue (212.4746.57)
Kotlin: 212-1.5.10-release-IJ4746.92

**Comment by shuzijun** [comment]
> IntelliJ IDEA 2021.2 (Ultimate Edition)
> 内部版本号 #IU-212.4746.92，July 27, 2021 构建
> 运行时版本: 11.0.11+9-b1504.13 amd64
> VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
> Windows 10 10.0
> GC: G1 Young Generation, G1 Old Generation
> Memory: 1300M
> Cores: 8
> Registry: ide.browser.jcef.enabled=false, javaee.legacy.project.wizard=true
> Non-Bundled Plugins: com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.11.1), com.intellij.zh (212.231), leetcode-editor (7.0), com.alibaba.p3c.smartfox (2.1.1), org.jetbrains.plugins.vue (212.4746.57)
> Kotlin: 212-1.5.10-release-IJ4746.92

需要启用JCEF，目前配置的信息禁用了ide.browser.jcef.enabled=false
启用方式，**Help** -> **Find Action..**,在输入框中输入**Registry**，在弹出框的输入框中找到**ide.browser.jcef.enabled**启用
@dmc-forwardtogether

**Comment by ZakAnun** [comment]
> @dmc-forwardtogether 提供下_Help_ -> _About_里的信息

Android Studio Arctic Fox | 2020.3.1 Patch 1
Build #AI-203.7717.56.2031.7621141, built on August 8, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi, leetcode-editor, org.jetbrains.kotlin, zielu.gittoolbox, com.chrisrm.idea.MaterialThemeUI

提示了以下信息，不清楚新版环境不支持 JCEF，之前的版本没问题。ide.browser.jcef.enabled 这个属性也已经设置为 true，不知道其他人有没有遇到这个问题。
Not Support JCEF: Your environment does not support JCEF, cannot use LeetCode Editor.Check the Registry 'ide.browser.jcef.enabled'.

**Comment by 2292384454** [comment]
如果提交每日一题的话，会发生题目对应不上的问题，比如我2021年8月23日的每日一题是1646，但是根据提交反馈的错误信息可以看出启动的是1539的判题程序。最最最重要的是：在此之后再点提交就会一直 error: 请求失败！！！
