### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by ijkzen** [shuzijun/leetcode-editor#384]
**Describe the bug**
输入正确的账户密码后, 点击登录, 显示登录失败

**Log**

```java
2021-08-23 10:41:34,134 [ 126175]  ERROR -  #com.shuzijun.leetcode.plugin - 登陆错误 
java.lang.IllegalArgumentException: Text may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)
	at org.apache.http.entity.mime.content.StringBody.<init>(StringBody.java:155)
	at org.apache.http.entity.mime.MultipartEntityBuilder.addTextBody(MultipartEntityBuilder.java:153)
	at org.apache.http.entity.mime.MultipartEntityBuilder.addTextBody(MultipartEntityBuilder.java:158)
	at com.shuzijun.leetcode.plugin.window.HttpLogin.ajaxLogin(HttpLogin.java:42)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:63)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-08-23 10:41:34,138 [ 126179]  ERROR -  #com.shuzijun.leetcode.plugin - IntelliJ IDEA 2021.2  Build #IU-212.4746.92 
2021-08-23 10:41:34,141 [ 126182]  ERROR -  #com.shuzijun.leetcode.plugin - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-08-23 10:41:34,141 [ 126182]  ERROR -  #com.shuzijun.leetcode.plugin - OS: Windows 10 
2021-08-23 10:41:34,141 [ 126182]  ERROR -  #com.shuzijun.leetcode.plugin - Plugin to blame: LeetCode Editor version: 7.3 
2021-08-23 10:41:34,141 [ 126182]  ERROR -  #com.shuzijun.leetcode.plugin - Last Action: leetcode.LoginAction 
2021-08-23 10:41:34,736 [ 126777]   WARN - rotocol.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: AWSALB=fab7VjEPw/46YNjDPuxHIq1V6XkBITwGU2atA8MX16rcdvMFR/BoQKaJF9yLKpUnFRCx2yGGjGsF4R9/E42uUVGkPT40proh8R0ZB7NY0IkhCLkaKq0ArBvE4CuB; Expires=Mon, 30 Aug 2021 02:41:34 GMT; Path=/". Invalid 'expires' attribute: Mon, 30 Aug 2021 02:41:34 GMT 
2021-08-23 10:41:34,737 [ 126778]   WARN - rotocol.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: AWSALBCORS=fab7VjEPw/46YNjDPuxHIq1V6XkBITwGU2atA8MX16rcdvMFR/BoQKaJF9yLKpUnFRCx2yGGjGsF4R9/E42uUVGkPT40proh8R0ZB7NY0IkhCLkaKq0ArBvE4CuB; Expires=Mon, 30 Aug 2021 02:41:34 GMT; Path=/; SameSite=None; Secure". Invalid 'expires' attribute: Mon, 30 Aug 2021 02:41:34 GMT 
```

**Comment by qinlg** [comment]
同样问题，用不了了。
