### ISSUE TITLE
error： Failed to send request

### ISSUE THREAD

**Issue by TABDONG** [shuzijun/leetcode-editor#392]
## 问题描述
之前偶尔会出现的情况：点击登陆会弹出cookie null的小框
最近总会出现单个action要好久的情况，多个action会排在一块等待执行；之前猜测网络，但连接测试打开网站速度都没问题
现在大部分action能正常运行，虽然要等挺长时间，但是 testcase 和 summit 就会报 error: Failed to send request

## 已经试过的解决方法
- 卸载pycharm和Clion中的插件（这俩装最开始是以为不同的软件装上就可以用不同的语言写，结果发现是相通的。。就一直放着没用）
- 删除插件缓存
- 删除IDEA缓存
- 重新安装插件，最新版前几版都试过
- 重新安装IDEA

## 错误日志
＞　java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.RunCodeCode(CodeManager.java:203)
	at com.shuzijun.leetcode.plugin.actions.editor.TestcaseAction.actionPerformed(TestcaseAction.java:44)
	at com.shuzijun.leetcode.plugin.actions.editor.AbstractEditAction.actionPerformed(AbstractEditAction.java:37)
	at com.shuzijun.leetcode.plugin.actions.editor.TestcaseAction.actionPerformed(TestcaseAction.java:20)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by shuzijun** [comment]
在 testcase 和 summit 未返回结果之前，再次提交就会出现上面的错误，这是leetcode的限制，下个版本增加提示.
