### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by dengj888** [shuzijun/leetcode-editor#402]
密码登录失败，然后拷贝cookie登录报错如下
java.lang.Throwable: login 400:null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.shuzijun.leetcode.plugin.window.HttpLogin.ajaxLogin(HttpLogin.java:85)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:63)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by PaulWongDlut** [comment]
账号密码+cookie登陆失败，报错：
保存文件错误

java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1035)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.saveFile(FileUtils.java:44)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.saveFile(FileUtils.java:32)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:54)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:53)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:49)
	at com.shuzijun.leetcode.plugin.actions.toolbar.RefreshAction.actionPerformed(RefreshAction.java:20)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by PaulWongDlut** [comment]
@shuzijun

**Comment by shuzijun** [comment]
> 账号密码+cookie登陆失败，报错：
> 保存文件错误
> 
> java.io.IOException: No such file or directory
> at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
> at java.base/java.io.File.createNewFile(File.java:1035)
> at com.shuzijun.leetcode.plugin.utils.FileUtils.saveFile(FileUtils.java:44)
> at com.shuzijun.leetcode.plugin.utils.FileUtils.saveFile(FileUtils.java:32)
> at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:54)
> at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:53)
> at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:49)
> at com.shuzijun.leetcode.plugin.actions.toolbar.RefreshAction.actionPerformed(RefreshAction.java:20)
> at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
> at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
> at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
> at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
> at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
> at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
> at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
> at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
> at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
> at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
> at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
> at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
> at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
> at java.base/java.security.AccessController.doPrivileged(Native Method)
> at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
> at java.base/java.lang.Thread.run(Thread.java:829)

检查配置的缓存目录是不是存在和有权限读取写入

**Comment by Stajo3** [comment]
看来大家都遇到了这个问题

**Comment by SakurajimaMaii** [comment]
Cookie登录显示空白
![image](https://user-images.githubusercontent.com/46998172/134444324-10b13bc4-b2ae-4163-b327-f88ae26eb17b.png)

**Comment by Stajo3** [comment]
> 看来大家都遇到了这个问题
cookie login的问题看到一篇博客上有，需要浏览器登陆leetcode之后F12，复制cookie，粘贴到IDEA cookielogin登陆框中。但我没找到复制的cookie。我最后用了另外一个方法，就是在leetcode插件设置中，勾选JCEF,会直接跳出网页登陆，不需要用cookie 登陆。解决!

**Comment by SakurajimaMaii** [comment]
谢谢Stajo3的解决方案，问题已经解决
