### ISSUE TITLE
无法打开新题目，文件创建错误。

### ISSUE THREAD

**Issue by kafmws** [shuzijun/leetcode-editor#488]
无法打开新题目，文件创建错误。
出现过程：
1. 登录
2. 点击获取到的任意题目
3. 报错如下
java.io.IOException: 文件名、目录名或卷标语法不正确。
	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1035)
	at com.shuzijun.leetcode.plugin.utils.FileUtils.saveFile(FileUtils.java:44)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.openContent(CodeManager.java:77)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.openCode(CodeManager.java:40)
	at com.shuzijun.leetcode.plugin.listener.TreeMouseListener$1.run(TreeMouseListener.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)

目录等文件正常产生了，但题目解答文件无法正常保存。重启CLion无效。
正常使用过1道题目，打开新题目出现该错误。
CLion 版本：Build #CL-221.5080.224, built on April 14, 2022
OS：Win10

**Comment by shuzijun** [comment]
检查下路径配置和code file name的配置是否正确。
这个错误是创建题目描述文件时无法创建，这个文件保存在题目目录/doc/content/里面
