### ISSUE TITLE
力扣中文站的URL从https://leetcode-cn.com/改成了https://leetcode.cn

### ISSUE THREAD

**Issue by huangyebiaoke** [shuzijun/leetcode-editor#491]
**Describe the bug**
关于LeetCode中文站域名更改的问题，如标题所示，希望能尽快更新或者给出临时解决方案。
谢谢作者的开源项目。

**To Reproduce**
1. Go to 'leecode editor slide panel'
2. Click on 'sign in'
3. pop website

**Software versions(*Help* -> *About*)**
- Product: [e.g IDEA 2021.3]
- LeetCode Editor (8.0)

**Question(Optional)**
- URL:[e.g leetcode-cn.com]
- Code Type:[e.g JAVA]
- code:
  ```
  HttpRequestUtils request error:
java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:115)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:109)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:151)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:137)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executePost(HttpRequestUtils.java:46)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:57)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:37)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LogoutAction.actionPerformed(LogoutAction.java:26)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
  ```

**Comment by Maskvvv** [comment]
上班不能刷题了难受

**Comment by shutdowner** [comment]
我用cookie好像也不能登录

**Comment by zhanglili31** [comment]
cookie和账号都不能登陆
![image](https://user-images.githubusercontent.com/26422454/167325695-ca90edbb-927a-4059-a7e4-c51933f4f48d.png)

**Comment by huangyebiaoke** [comment]
临时解决办法如下：
1. 关闭IDEA；
2. 打开`C:\Users\huang\AppData\Roaming\JetBrains\IntelliJIdea2021.3\options`下的`leetcode-config.xml`文件；
3. 将里面的`leetcode-cn.com`字段替换成`leetcode.cn`(有两处)；
4. 启动IDEA 点击sign in按钮
相关源码在这里[@State(name = "PersistentConfig" + PluginConstant.ACTION_SUFFIX, storages = {@Storage(value = PluginConstant.ACTION_PREFIX + "-config.xml", roamingType = RoamingType.DISABLED)})](https://github.com/shuzijun/leetcode-editor/blob/afe995f53b17772fa2010f732d72f7f6efb392a7/src/main/java/com/shuzijun/leetcode/plugin/setting/PersistentConfig.java#L22)
![image](https://user-images.githubusercontent.com/26546591/167326044-10d0e8fe-5aee-4874-b9ae-970d4e7a94de.png)

**Comment by huangyebiaoke** [comment]
> 上班不能刷题了难受

出了一个临时解决方案可以看一下，请愉快得刷题吧😀

**Comment by huangyebiaoke** [comment]
> 我用cookie好像也不能登录

请看临时解决方案

**Comment by huangyebiaoke** [comment]
> cookie和账号都不能登陆 ![image](https://user-images.githubusercontent.com/26422454/167325695-ca90edbb-927a-4059-a7e4-c51933f4f48d.png)

请看临时解决方案

**Comment by shuzijun** [comment]
正在改，中午发布

**Comment by huangyebiaoke** [comment]
> 正在改，中午发布

谢谢您，期待

**Comment by judgebymom** [comment]
发布后需要重新下载新版本吗？

**Comment by judgebymom** [comment]
临时方法有用，但是我的leetcode-config.xml文件是在C:\Users\YT-007\.IntelliJIdea2019.3\config\options，全局搜出来的

**Comment by ChenChengle** [comment]
临时方法有用，macOS系统下面，配置文件是在~/Library/Application Support/JetBrains/IntelliJIdea2021.3/options

**Comment by Stutter67** [comment]
临时方法有用  但具体的路径可以看看安装路径下的bin文件夹子里的idea.properties文件中的idea.config.path   在对应的config路径下的options

**Comment by Kamisamakk** [comment]
好使

**Comment by huhu-jin** [comment]
for linux:
```
vim .config/JetBrains/IntelliJIdea2021.3/options/leetcode-config.xml
```

**Comment by shuaixiaomi** [comment]
请问，不能运行代码和提交也是这个原因吗

**Comment by likuoBlog** [comment]
> 
是的，今天全都不能用了。
静等补丁

**Comment by huangyebiaoke** [comment]
> 请问，不能运行代码和提交也是这个原因吗

您好，应该是的。静等作者更新吧

**Comment by shuzijun** [comment]
修复版本[v8.1](https://github.com/shuzijun/leetcode-editor/releases/tag/v8.1)

**Comment by dakangshuji** [comment]
> 临时解决办法如下：
> 
> 1. 关闭IDEA；
> 2. 打开`C:\Users\huang\AppData\Roaming\JetBrains\IntelliJIdea2021.3\options`下的`leetcode-config.xml`文件；
> 3. 将里面的`leetcode-cn.com`字段替换成`leetcode.cn`(有两处)；
> 4. 启动IDEA 点击sign in按钮
>    相关源码在这里[@State(name = "PersistentConfig" + PluginConstant.ACTION_SUFFIX, storages = {@Storage(value = PluginConstant.ACTION_PREFIX + "-config.xml", roamingType = RoamingType.DISABLED)})](https://github.com/shuzijun/leetcode-editor/blob/afe995f53b17772fa2010f732d72f7f6efb392a7/src/main/java/com/shuzijun/leetcode/plugin/setting/PersistentConfig.java#L22)
>    ![image](https://user-images.githubusercontent.com/26546591/167326044-10d0e8fe-5aee-4874-b9ae-970d4e7a94de.png)

加一句，改完之后记得重新启动一下idea，需要让idea重新加载一下改过的配置文件，登录才能生效

**Comment by dakangshuji** [comment]
亲测可用，感谢临时方案~

**Comment by TU-RUI** [comment]
mac 电脑的leetcode-config.xml路径在 /Users/turui/Library/Application Support/JetBrains/IntelliJIdea2020.1/options

**Comment by wangwei216** [comment]
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/33742054/173320155-279738e8-8c74-45dc-80f0-dc381913dd6a.png">
直接点插件中的设置，Mac 直接修改 url 就行了

**Comment by monickey** [comment]
> 临时解决办法如下：
> 
> 1. 关闭IDEA；
> 2. 打开`C:\Users\huang\AppData\Roaming\JetBrains\IntelliJIdea2021.3\options`下的`leetcode-config.xml`文件；
> 3. 将里面的`leetcode-cn.com`字段替换成`leetcode.cn`(有两处)；
> 4. 启动IDEA 点击sign in按钮
>    相关源码在这里[@State(name = "PersistentConfig" + PluginConstant.ACTION_SUFFIX, storages = {@Storage(value = PluginConstant.ACTION_PREFIX + "-config.xml", roamingType = RoamingType.DISABLED)})](https://github.com/shuzijun/leetcode-editor/blob/afe995f53b17772fa2010f732d72f7f6efb392a7/src/main/java/com/shuzijun/leetcode/plugin/setting/PersistentConfig.java#L22)
>    ![image](https://user-images.githubusercontent.com/26546591/167326044-10d0e8fe-5aee-4874-b9ae-970d4e7a94de.png)

请问
<map>
        <entry key ="leetcode.cnmonickey@hotmail.com" value=“[{&quot;path&quot;:&quot;/&quot;,&quot;domain&quot;:&quot;leetcode.cn&quot
后面的内容是什么？截图不全。我的

> 临时解决办法如下：
> 
> 1. 关闭IDEA；
> 2. 打开`C:\Users\huang\AppData\Roaming\JetBrains\IntelliJIdea2021.3\options`下的`leetcode-config.xml`文件；
> 3. 将里面的`leetcode-cn.com`字段替换成`leetcode.cn`(有两处)；
> 4. 启动IDEA 点击sign in按钮
>    相关源码在这里[@State(name = "PersistentConfig" + PluginConstant.ACTION_SUFFIX, storages = {@Storage(value = PluginConstant.ACTION_PREFIX + "-config.xml", roamingType = RoamingType.DISABLED)})](https://github.com/shuzijun/leetcode-editor/blob/afe995f53b17772fa2010f732d72f7f6efb392a7/src/main/java/com/shuzijun/leetcode/plugin/setting/PersistentConfig.java#L22)
>    ![image](https://user-images.githubusercontent.com/26546591/167326044-10d0e8fe-5aee-4874-b9ae-970d4e7a94de.png)

请问
 <map>
        <entry key ="leetcode.cnmonickey@hotmail.com" value=“[{&quot;path&quot;:&quot;/&quot;,&quot;domain&quot;:&quot;leetcode.cn&quot
后面是什么？截图显示不全。而我的leetcode-config.xml上没有这一行
