### ISSUE TITLE
常见问题

### ISSUE THREAD

**Issue by shuzijun** [shuzijun/leetcode-editor#53]
**Q:提示登录失败**  
A:建议检查一下登录账号和密码，是否和所选择的网站对应，两个网站的账号是不互通的。  
  
**Q:提示无法判断登录状态**  
A:这个异常发生在部分账号上，目前没有找到产生的原因，建议先检查用户名密码是否填写，再通过网页版登录一下，确定登录账号正常，然后再在插件里登录  

**Q:获取\*\*异常**  
A:这类问题主要出现在网络问题，可以通过ide右下角的提示信息查看具体错误，例如:"java.net.SocketTimeoutException: Read timed out"，如果遇到不能识别的错误，可以通过错误提示框下方的按钮"提报给作者"进行反馈  
  
**Q:提示错误java.net.SocketTimeoutException: Read timed out**  
A:此类问题多数出现在网络差的情况下，建议先通过网页访问网站，测试网络是否有问题。  

**Q: Icon cannot be found in 'AllIcons.General.OpenDiskHover'**  
A:出现在一些低版本上，没有这个图标，下个版本更换此图标  
  
**Q:javax.net.ssl.SSLException: Unexpected rethrowing**  
A:此类问题一直没有复现，也没有找到具体产生的原因，有了解的可以交流一下  

**Q:Element component@PersistentConfig.option.Config.option.@name=password probably contains sensitive information**  
A:此问题是由于低版本序列化时没有排除掉密码，在新版中已经修复。

**Comment by marvinxu-free** [comment]
提示账户或密码没有设置，但是实际上配置了，回去看密码都是空的，这是什么原因？

**Comment by shuzijun** [comment]
> 提示账户或密码没有设置，但是实际上配置了，回去看密码都是空的，这是什么原因？

最新版的加强了对密码的控制，如果是从低版本升级的，第一次使用需要重新配置密码，再次使用就不会出现此问题。如果还有此问题，麻烦提供下机器的系统，IDE的版本

**Comment by marvinxu-free** [comment]
IDE升级的最新版本2019.02, macos也是最新更新的.

**Comment by shuzijun** [comment]
> IDE升级的最新版本2019.02, macos也是最新更新的.
@marvinxu-free 现在还是无法保存密码？

**Comment by shuzijun** [comment]
> 现在好了，你们做了什么操作？

只有升级之后第一次会出现这种情况

**Comment by CheungQ** [comment]
今天的问题，报json解析异常后更新了7.4，登录有问题，提示登录成功，但是每次提交还是会让重新登陆，最后去idea配置文件中把原来的插件配置删掉了，重新填账号密码才可以登陆成功。然后新问题，今天的每日一题1646会提交到1539题，1539题会提交到1424题，后面每再继续往下看了，
感谢作者，摸鱼神器

**Comment by nanshoudabaojian** [comment]
插件更新后题解变成了lcv文件？

**Comment by medmin** [comment]
请问Pro版本和这个有什么区别？

**Comment by shuzijun** [comment]
> 请问Pro版本和这个有什么区别？

功能上没什么区别，有些功能会在pro版本上先发布，其他一样

**Comment by qihuaiyu** [comment]
原来直接用plugin market 的 Leetcode-editor 6.9版本没法登陆账户，点击登陆的时候显示需要输入cookies,
<img width="433" alt="image" src="https://user-images.githubusercontent.com/31617882/174480744-6162ca7d-4063-4088-a1e8-35aefbb08572.png">
,不知道这个cookies应该填什么？直接把8.1的zip包拖进clion(2022.1版本)之后显示: Plugin 'LeetCode Editor Pro' is incompatible with this installation, 
![image](https://user-images.githubusercontent.com/31617882/174480491-59d82b01-c353-4246-8da0-1eb5b182a97a.png)，这是怎么回事？

**Comment by shuzijun** [comment]
@qihuaiyu https://github.com/shuzijun/leetcode-editor/issues/491 有临时解决方案
https://github.com/shuzijun/leetcode-editor/issues/497 有相关版本发布说明

**Comment by zhaogeyuan** [comment]
现在为啥没有专题Tag的列表了?

**Comment by SHIFFF** [comment]
第一次使用，在点击题目的时候报错，页面出不来，异常是java.io.IOException，消息内容为“没有这样的文件或目录”。
java.io.IOException: No such file or directory
![image](https://github.com/shuzijun/leetcode-editor/assets/55538843/3638fa95-27b0-4774-9b36-c095002763b3)

**Comment by Lilith-2001** [comment]
登录成功，在右键题目java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.vfs.VirtualFile.getPath()" because "vf" is null
	at com.shuzijun.leetcode.plugin.utils.FileUtils.openFileEditorAndSaveState(FileUtils.java:233)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.openContent(CodeManager.java:79)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.openCode(CodeManager.java:40)
	at com.shuzijun.leetcode.plugin.actions.tree.OpenAction.actionPerformed(OpenAction.java:16)
	at com.shuzijun.leetcode.plugin.actions.tree.AbstractTreeAction.actionPerformed(AbstractTreeAction.java:33)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Lilith-2001** [comment]
> 第一次使用，在点击题目的时候报错，页面出不来，异常是java.io.IOException，消息内容为“没有这样的文件或目录”。 java.io.IOException: No such file or directory ![image](https://private-user-images.githubusercontent.com/55538843/319097864-3638fa95-27b0-4774-9b36-c095002763b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTYzNDcsIm5iZiI6MTcyNDY1NjA0NywicGF0aCI6Ii81NTUzODg0My8zMTkwOTc4NjQtMzYzOGZhOTUtMjdiMC00Nzc0LTliMzYtYzA5NTAwMjc2M2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA3MDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MTUwNDYwODQwNWQ1ZjZkYTIwYTViMTJmOGM2MGIzZGFjZGUwZDJhMmMyZGI2ZmM2ODAyOTM3MDBiMDkyZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OgpmmHSmPobrEbk82f2HHUdetZqo1WTDReL13kzHnGM)

一样的，解决了吗
