### ISSUE TITLE
IDEA 2020.3 无法打开题目

### ISSUE THREAD

**Issue by EruDev** [shuzijun/leetcode-editor#608]
**Describe the bug**
- 双击打不开题目
- open question 打不开题目

右下角报错日志 (stacktrace.txt)

```java
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/openapi/fileEditor/FileEditorManager.getInstance must not be null
	at com.intellij.openapi.fileEditor.FileEditorManager.$$$reportNull$$$0(FileEditorManager.java)
	at com.intellij.openapi.fileEditor.FileEditorManager.getInstance(FileEditorManager.java)
	at com.a.a.a.a.a.r.getChildren(CodeActionGroup.java:25)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$3(ActionUpdater.java:98)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:134)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$4(ActionUpdater.java:98)

```

**Comment by shuzijun** [comment]
是否已经打开了一个项目？

**Comment by EruDev** [comment]
> 是否已经打开了一个项目？

是打开了一个项目

**Comment by shuzijun** [comment]
方便截下窗口的图片么？

**Comment by EruDev** [comment]
> 方便截下窗口的图片么？

![image](https://user-images.githubusercontent.com/31091355/210307781-8c5f7112-cc5f-43e3-bf71-58c7b29fcd5c.png)

**Comment by EruDev** [comment]
> 方便截下窗口的图片么？

![image](https://user-images.githubusercontent.com/31091355/210307878-24a55603-f184-4ce6-87d7-89d11c4818a9.png)

**Comment by shuzijun** [comment]
IDE的版本是多少？

**Comment by shuzijun** [comment]
IDE的版本是多少？

**Comment by EruDev** [comment]
> 可能版本有点低，我找个2020.3的试试

感谢，版本是 2020.3，那我更新下 IDEA 版本

**Comment by shuzijun** [comment]
> 感谢，版本是 2020.3，那我更新下 IDEA 版本
测试了一下，2020.3确实有兼容性问题，先升级版本吧
