### ISSUE TITLE
Not able to login to leetcode from plugin

### ISSUE THREAD

**Issue by shrawanraina** [shuzijun/leetcode-editor#672]
**Describe the bug**
Unable to login to leetcode

**To Reproduce**
1. Open IntelliJ
2. Click on Leetcode Editor plugin
3. Click on Sign In
4. Error: Failed to send request

java.lang.Throwable: Request userStatus  failed, status:403
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getUser(QuestionManager.java:315)
	at com.shuzijun.leetcode.plugin.window.NavigatorTabsPanel.getUser(NavigatorTabsPanel.java:176)
	at com.shuzijun.leetcode.plugin.window.NavigatorTabsPanel.lambda$new$0(NavigatorTabsPanel.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Software versions(*Help* -> *About*)**
- Product: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
- Runtime version:17.0.5+1-b653.25 x86_64
- VM:OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS: macOS Big Sur

**Comment by deerHDE** [comment]
I'm running into the exact same issue just now.

**Comment by rajvanshipradeep15** [comment]
Same here not able to login.

**Comment by rajvanshipradeep15** [comment]
I followed this link and I was able to login.
https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp.md

**Comment by selva-krishnan** [comment]
@rajvanshipradeep15  - I never got the popup to enter the cookie information as shown in the screenshot. All I get is the "Failed to send request" in the console.

**Comment by tech1savvy** [comment]
> @rajvanshipradeep15 - I never got the popup to enter the cookie information as shown in the screenshot. All I get is the "Failed to send request" in the console.

+1

**Comment by akhilss99** [comment]
> @rajvanshipradeep15 - I never got the popup to enter the cookie information as shown in the screenshot. All I get is the "Failed to send request" in the console.

+1

**Comment by shuzijun** [comment]
@selva-krishnan @tech1savvy @akhilss99 This is a new issue, please refer to #697

**Comment by rajvanshipradeep15** [comment]
Hello guys, just make sure you have the right settings in the PHPSTORM 
<img width="1440" alt="settings_leetcode" src="https://github.com/shuzijun/leetcode-editor/assets/3005720/54b30b40-5f44-47bd-96c7-2bd933d408ce">

Later when you click the signin button you should get the login popup, as shown in the screen shot.
<img width="1440" alt="leetcode_login" src="https://github.com/shuzijun/leetcode-editor/assets/3005720/c1667f5c-5c26-4a8b-9b9e-426eafc8a6a6">
