### ISSUE TITLE
设置界面一直加载并报错

### ISSUE THREAD

**Issue by actforjason** [shuzijun/leetcode-editor#684]
> IntelliJ IDEA 2023.3.1 (Ultimate Edition)
leetcode-editor 8.9

![图片](https://github.com/shuzijun/leetcode-editor/assets/57058325/108805fe-4e76-48ef-8d26-2ff3cf94876d)

> cannot create configurable component
java.lang.NullPointerException: Cannot invoke "javax.swing.JComboBox.addItem(Object)" because "this.webComboBox" is null
	at com.shuzijun.leetcode.plugin.setting.SettingUI.initUI(SettingUI.java:82)
	at com.shuzijun.leetcode.plugin.setting.SettingUI.<init>(SettingUI.java:77)
	at com.shuzijun.leetcode.plugin.setting.SettingConfigurable.createComponent(SettingConfigurable.java:48)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:181)

> java.lang.NullPointerException: Cannot invoke "com.shuzijun.leetcode.plugin.setting.SettingUI.isModified()" because "this.mainPanel" is null
	at com.shuzijun.leetcode.plugin.setting.SettingConfigurable.isModified(SettingConfigurable.java:54)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.isModified(ConfigurableWrapper.java:186)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedInternal(SettingsEditor.java:522)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedForItem(SettingsEditor.java:516)

**Comment by actforjason** [comment]
打包时需要选择`instrumentedJar`
