### ISSUE TITLE
MalformedURLException: no protocol: /problemset/

### ISSUE THREAD

**Issue by Elward-lv** [shuzijun/leetcode-editor#694]
**点击登录之后提示请求错误 IDEA提示堆栈如下**
  HttpRequestUtils request error:
  
  java.net.MalformedURLException: no protocol: /problemset/
at java.base/java.net.URL.<init>(URL.java:674)
at java.base/java.net.URL.<init>(URL.java:569)
at java.base/java.net.URL.<init>(URL.java:516)
at com.intellij.util.net.HttpConfigurable.openConnection(HttpConfigurable.java:375)
at com.intellij.openapi.fileEditor.impl.IdeUiServiceImpl.openHttpConnection(IdeUiServiceImpl.java:138)
at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:558)
at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:361)
at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:177)
at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:160)
at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:524)
at com.intellij.util.io.HttpRequests.process(HttpRequests.java:506)
at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:335)
at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.lambda$executeGet$1(HttpRequestUtils.java:45)
at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$CacheProcessor.processor(HttpRequestUtils.java:214)
at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executeGet(HttpRequestUtils.java:39)
at com.shuzijun.leetcode.plugin.model.HttpRequest$HttpRequestBuilder.request(HttpRequest.java:163)
at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:33)
at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

这个是我本地网络协议有问题吗

**Comment by WuWen3011** [comment]
我遇到了同样的问题，请问你解决了嘛

**Comment by falmehknight** [comment]
我也遇到了，通过cookie登录就可以了。
