### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ShaunTheCode** [shuzijun/leetcode-editor#708]
java.lang.NullPointerException: Cannot invoke "java.net.PasswordAuthentication.getUserName()" because "authentication" is null
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$MyExecutorHttp.lambda$getProxyAuthenticator$0(HttpRequestUtils.java:203)
	at okhttp3.internal.connection.RealConnection.createTunnelRequest(RealConnection.kt:519)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:258)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.shuzijun.lc.http.DefaultExecutoHttp.lambda$executePost$2(DefaultExecutoHttp.java:115)
	at com.shuzijun.lc.http.InterceptorChain.proceed(InterceptorChain.java:36)
	at com.shuzijun.lc.http.DefaultExecutoHttp.executePost(DefaultExecutoHttp.java:124)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.lambda$executePost$2(HttpRequestUtils.java:98)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$CacheProcessor.processor(HttpRequestUtils.java:160)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executePost(HttpRequestUtils.java:90)
	at com.shuzijun.leetcode.plugin.model.HttpRequest$HttpRequestBuilder.request(HttpRequest.java:165)
	at com.shuzijun.leetcode.plugin.model.Graphql$GraphqlBuilder.request(Graphql.java:136)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getUser(QuestionManager.java:299)
	at com.shuzijun.leetcode.plugin.window.NavigatorTabsPanel.getUser(NavigatorTabsPanel.java:176)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionAllService(QuestionManager.java:66)
	at com.shuzijun.leetcode.plugin.manager.CodeTopManager.loadServiceData(CodeTopManager.java:24)
	at com.shuzijun.leetcode.plugin.manager.CodeTopManager.loadServiceData(CodeTopManager.java:20)
	at com.shuzijun.leetcode.plugin.window.navigator.TopNavigatorPanel$3.findClear(TopNavigatorPanel.java:117)
	at com.shuzijun.leetcode.plugin.actions.toolbar.RefreshAction.actionPerformed(RefreshAction.java:20)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Software versions**
- Product: IntelliJ IDEA 2023.3.6 (Ultimate Edition)
- Runtime version: 17.0.10+1-b1087.23 amd64
- VM:OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS:Windows 10

**Comment by zhatlas** [comment]
Having the same problem

**Comment by shuzijun** [comment]
<img width="733" alt="image" src="https://github.com/shuzijun/leetcode-editor/assets/27667179/f610ddbb-0d43-4509-9927-54e62fd7d5b3">


"Proxy authentication" was selected but the authentication information was not filled in?

**Comment by zhatlas** [comment]
It's me, I'm sure I've checked Proxy authentication and entered my username and password and tested google access using Check connection and it's accessible!

**Comment by Qiliqing** [comment]
Having the same problem

**Comment by rcj60560** [comment]
@shuzijun 
我也是这个问题。。。

**Comment by hejianzhong** [comment]
我也是这个问题呀 QAQ @shuzijun

**Comment by sjjok00** [comment]
Try uncheck "Proxy authentication"

> <img alt="image" width="733" src="https://private-user-images.githubusercontent.com/27667179/321487169-f610ddbb-0d43-4509-9927-54e62fd7d5b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjI3ODUsIm5iZiI6MTcxNTc2MjQ4NSwicGF0aCI6Ii8yNzY2NzE3OS8zMjE0ODcxNjktZjYxMGRkYmItMGQ0My00NTA5LTk5MjctNTRlNjJmZDdkNWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA4NDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YTI1OTE5YzJmYjY3NGJhNTBhNTkxNWM3OTU1YWNlNWE1NWVkZjFkZDMzZTk0NTZiOTgxOTA5NjU3OTM3YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.94FRvIxSMgsHPfmEydx9LsiwzbXKi9697s2VntzT-Xc">
> "Proxy authentication" was selected but the authentication information was not filled in?
