### ISSUE TITLE
刷新题目失败

### ISSUE THREAD

**Issue by ApostleTubriss** [shuzijun/leetcode-editor#71]
![image](https://user-images.githubusercontent.com/28864923/65780431-4ae18a00-e17c-11e9-870f-acfd69d57a10.png)

java.lang.NumberFormatException: For input string: "LCP 3"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager$3.compare(QuestionManager.java:221)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager$3.compare(QuestionManager.java:218)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:234)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1749)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.parseQuestion(QuestionManager.java:218)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:49)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:34)
	at com.shuzijun.leetcode.plugin.actions.LoginAction.perform(LoginAction.java:94)
	at com.shuzijun.leetcode.plugin.actions.AbstractAsynAction$1.run(AbstractAsynAction.java:17)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by zhangxingits** [comment]
我的也是，这是什么原因啊，急急急

**Comment by flyfire** [comment]
对，我的idea也报这个错误，leetcode-cn网站的，之前一直正常，今天刷新题目失败了

**Comment by 15626471095** [comment]
+1

**Comment by flyfire** [comment]
https://github.com/shuzijun/leetcode-editor/pull/70 ，已经有人提交了PR，麻烦尽快合并，更新插件

**Comment by wvdon** [comment]
+1我也是出现这个问题了

**Comment by xiaopo1991** [comment]
+1

**Comment by raymondsryang** [comment]
+1

**Comment by shuzijun** [comment]
正在处理

**Comment by shuzijun** [comment]
插件已临时更新到5.2版本，插件库需要审核一段时间，可以先通过硬盘安装，[下载地址](https://raw.githubusercontent.com/shuzijun/leetcode-editor/master/doc/leetcode-editor-V5.2.zip)
