### ISSUE TITLE
关于近两天leetcode-cn列表无法展示问题

### ISSUE THREAD

**Issue by shuzijun** [shuzijun/leetcode-editor#73]
中文站的leetcode增加了几道题目，编号为LCP 1。由于设计的题目列表排序时是按照数字进行排序的，然后就导致了列表无法展示的问题。
:joy: 不清楚为什么会改变编号规则，设计的时候也没有考虑非数字的情况，导致无法使用的情况，深感抱歉，已经临时修复了排序方式，版本为5.2，插件库更新需要一段时间的审核，可以先通过硬盘安装，[下载地址](https://raw.githubusercontent.com/shuzijun/leetcode-editor/master/doc/leetcode-editor-V5.2.zip)

**Comment by shinalone** [comment]
退出登录（首次）加载会有这个问题！
还有我看别人直接显示中文目录（leetcode-cn）？
提交代码会有缩进错误？（pycharm缩进一直正常使用）

```
java.lang.NumberFormatException: For input string: "LCP 3"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.valueOf(Unknown Source)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager$3.compare(QuestionManager.java:221)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager$3.compare(QuestionManager.java:218)
	at java.base/java.util.TimSort.countRunAndMakeAscending(Unknown Source)
	at java.base/java.util.TimSort.sort(Unknown Source)
	at java.base/java.util.Arrays.sort(Unknown Source)
	at java.base/java.util.ArrayList.sort(Unknown Source)
	at java.base/java.util.Collections.sort(Unknown Source)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.parseQuestion(QuestionManager.java:218)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestionService(QuestionManager.java:49)
	at com.shuzijun.leetcode.plugin.manager.ViewManager.loadServiceData(ViewManager.java:34)
	at com.shuzijun.leetcode.plugin.actions.LoginAction.perform(LoginAction.java:94)
	at com.shuzijun.leetcode.plugin.actions.AbstractAsynAction$1.run(AbstractAsynAction.java:17)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by raymondsryang** [comment]
感谢大大快速的修复:)

**Comment by shuzijun** [comment]
@shinalone 
1.是更新了新版本还有NumberFormatException的问题么？
2.显示中文目录可以在配置里选择URL为leetcode-cn。
3.提交时是不会改变缩进的，如果方便提供下对应的题目和解题的代码文件

**Comment by Jemair** [comment]
大佬这个版本是不是忘了这个
https://github.com/shuzijun/leetcode-editor/issues/57#issuecomment-529806017

**Comment by shuzijun** [comment]
> 大佬这个版本是不是忘了这个
> [＃57（评论）](https://github.com/shuzijun/leetcode-editor/issues/57#issuecomment-529806017)

这个版本里还有一些功能没测试过，这次没有一块发布
