### ISSUE TITLE
8.14 插件安装后，登陆请求失败

### ISSUE THREAD

**Issue by newbens** [shuzijun/leetcode-editor#734]
com.shuzijun.lc.errors.LcException: executePost error
	at com.shuzijun.lc.http.DefaultExecutoHttp.lambda$executePost$2(DefaultExecutoHttp.java:122)
	at com.shuzijun.lc.http.InterceptorChain.proceed(InterceptorChain.java:36)
	at com.shuzijun.lc.http.DefaultExecutoHttp.executePost(DefaultExecutoHttp.java:124)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.lambda$executePost$2(HttpRequestUtils.java:104)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$CacheProcessor.processor(HttpRequestUtils.java:166)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executePost(HttpRequestUtils.java:96)
	at com.shuzijun.leetcode.plugin.model.HttpRequest$HttpRequestBuilder.request(HttpRequest.java:165)
	at com.shuzijun.leetcode.plugin.model.Graphql$GraphqlBuilder.request(Graphql.java:136)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getUser(QuestionManager.java:299)
	at com.shuzijun.leetcode.plugin.window.NavigatorTabsPanel.getUser(NavigatorTabsPanel.java:176)
	at com.shuzijun.leetcode.plugin.window.NavigatorTabsPanel.lambda$new$0(NavigatorTabsPanel.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Unexpected response code for CONNECT: 405
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:483)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.shuzijun.lc.http.DefaultExecutoHttp.lambda$executePost$2(DefaultExecutoHttp.java:115)
	... 20 more

**Comment by newbens** [comment]
idea 2023.3。6

**Comment by newbens** [comment]
idea 版本2023.3.6
