### ISSUE TITLE
Pycharm Runcode和Testcase出错

### ISSUE THREAD

**Issue by isaaczhou** [shuzijun/leetcode-editor#78]
Pycharm 2019.2 使用 leetcode.com原站的时候可以提交，不过Runcode和Testcase的话会出错。以下是截图
![Capture](https://user-images.githubusercontent.com/26254354/66586143-27441980-eb56-11e9-9a38-40131efca6a2.PNG)

Exception report
```
提交出错，body:{"status_code": 10, "lang": "python3", "run_success": true, "status_runtime": "48 ms", "memory": 13672000, "code_answer": ["true"], "code_output": [], "expected_status_code": 10, "expected_lang": "cpp", "expected_run_success": true, "expected_status_runtime": "8", "expected_memory": 7904000, "expected_code_answer": ["true"], "expected_code_output": [], "correct_answer": true, "total_correct": null, "total_testcases": null, "runtime_percentile": null, "status_memory": "13.7 MB", "memory_percentile": null, "pretty_lang": "Python3", "submission_id": "runcode_1570723371.0935075_7U4XoQAQyo", "status_msg": "Accepted", "state": "SUCCESS"},returnObj:{"interpret_id":"runcode_1570723371.0935075_7U4XoQAQyo","test_case":"\"A man, a plan, a canal: Panama\""}

java.lang.NullPointerException
	at com.shuzijun.leetcode.plugin.manager.CodeManager$RunCodeCheckTask.run(CodeManager.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by shuzijun** [comment]
升级一下这个版本 [5.4](https://github.com/shuzijun/leetcode-editor/blob/master/doc/leetcode-editor-V5.4.zip)，leetcode.com更换了返回内容，旧版取不到返回值了，导致一直无法显示提交结果
