### ISSUE TITLE
运行或提交代码，显示error:请求失败

### ISSUE THREAD

**Issue by maoturing** [shuzijun/leetcode-editor#79]
提交时显示`error: 请求失败`，没有找到具体原因，请问有没有好的解决办法？

**Comment by shuzijun** [comment]
出现错误在右下角有个红色背景的叹号，里面有详细的错误日志提供一下

**Comment by marsprince** [comment]
java.lang.Throwable: 提交失败：url：/problems/kth-largest-element-in-an-array/submit/;param:{"typed_code":"/**\n * @param {number[]} nums\n * @param {number} k\n * @return {number}\n */\nvar findKthLargest = function(nums, k) {\n  // 1.鍋囧畾nums鏄竴涓畬鍏ㄤ簩鍙夋爲\n  // 2.瀹屽叏浜屽弶鏍戞�ц川锛宺oot鐨勫乏瀛愯妭鐐逛负2k+1,鍙宠妭鐐逛负2k+2\n  // 鏋勫缓鍫�\n  // 浠庢渶鍚庨潪鍙跺瓙鑺傜偣寮�濮嬶紝鐩村埌鏍硅妭鐐硅繘琛屾瘮杈冿紝濡傛灉灏忎簬锛堝ぇ浜庯級瀛╁瓙鑺傜偣鐨勬渶灏忥紙鏈�澶э級鍊硷紝鍒欎氦鎹綅缃紝鐒跺悗缁х画鍜屼笅涓�灞傚瀛愭瘮杈冪洿鍒版垚涓哄彾瀛愯妭鐐规垨婊¤冻澶у皬瑕佹眰\n  // 鏈�鍚庣殑闈炲彾瀛愯妭鐐� Math.floor(length / 2) - 1\n  // 姹傚墠K涓紝寤虹珛涓�涓狵鏈�灏忓爢鍗冲彲\n\n  function siftUp(array, index, length) {\n    for (let i = 2 * index + 1; i < length; i = 2 * i + 1) {\n      // 濡傛灉鍙宠妭鐐规瘮宸﹁妭鐐瑰ぇ锛屽垯鍓嶈繘\n      if (i + 1 < length && array[i + 1] < array[i]) {\n        i++;\n      }\n      // 姣旇緝锛屽鏋滃皬锛屽垯浜ゆ崲鍊硷紝骞跺皢index璁句负i锛坕ndex浠ｈ〃root锛岃姣旇緝鐨勬牴鑺傜偣锛�\n      if (array[index] <= [array[i]]) {\n        break;\n      } else {\n        [array[index], array[i]] = [array[i], array[index]];\n        index = i;\n      }\n    }\n  }\n\n  function buildMinHeap(arr, length) {\n    for (let i = Math.floor(length / 2) - 1; i >= 0; i--) {\n      siftUp(arr, i, length);\n    }\n  }\n\n  buildMinHeap(nums, k)\n  for(let i=k;i<nums.length;i++) {\n    if(nums[i] > nums[0]) {\n      [nums[0], nums[i]] = [nums[i], nums[0]];\n      siftUp(nums, 0, k)\n    }\n  }\n\n  return nums[0]\n};\n","lang":"javascript","question_id":"215"};body:<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://assets.leetcode.com/static_assets/templates/nginx_static_pages/styles/50x.css"/>
</head>
<body>
  <div class="container">
    <div class="display-503 row col-md-8 col-md-offset-2">
      <div class="col-md-6">
        <img class="face-image" src="https://assets.leetcode.com/static_assets/templates/nginx_static_pages/images/503.png" width="250px" alt="We'll be back" />
      </div>
      <div class="col-md-6 msg">
        <h2><strong>Oops. Internal Server Error.</strong></h2>
        <p>Please try again later.</p>
        <br>
        <a class="btn btn-default" data-toggle="modal" data-target="#supportModal"><i class="fa fa-envelope-o" aria-hidden="true"></i>&nbsp;  Contact Us</a>
      </div>
    </div>
  </div> 
  <footer class="site-footer">
    <div class="container">
      <hr>
      <div class="row">
        <div class="col-sm-5 copyright">
          <span>Copyright © 2018 LeetCode</span>
        </div>
        <div class="text-right col-sm-7 contact">
          <a data-toggle="modal" data-target="#supportModal">Contact Us</a>
        </div>
      </div>
      <div class="row"><p></p></div>
    </div>
   </div>
  </footer>
</body>


<div class="modal fade simple-modal" id="supportModal" role="dialog">
  <div class="modal-center">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <span class="text-lg text-300">&nbsp;How can we help you?</span>
        </div>

        <div class="modal-body">
          <div class="row text-center">
            <div class="col-sm-4">
              <a
                class="support-module btn btn-default"
                href="mailto:billing@leetcode.com?subject=Billing%20Issue&body=Name:%0D%0A%0D%0AUsername:%0D%0A%0D%0AMessage:%0D%0A%0D%0A"
                target="_blank"
              >
                <i class="fa fa-credit-card text-xl" aria-hidden="true"></i>
                <br/><span class="text">Billing &amp; Account</span>
              </a>
            </div>
            <div class="col-sm-4">
              <a
                class="support-module btn btn-default"
                href="mailto:support@leetcode.com?subject=General%20Support&body=Name:%0D%0A%0D%0AUsername:%0D%0A%0D%0AMessage:%0D%0A%0D%0A"
                target="_blank"
              >
                <i class="fa fa-life-ring text-xl" aria-hidden="true"></i>
                <br/><span class="text">General Support</span>
              </a>
            </div>
            <div class="col-sm-4">
              <a
                class="support-module btn btn-default"
                href="mailto:feedback@leetcode.com?subject=Other%20Inquiries&body=Name:%0D%0A%0D%0AUsername:%0D%0A%0D%0AMessage:%0D%0A%0D%0A"
                target="_blank"
              >
                <i class="fa fa-question-circle text-xl" aria-hidden="true"></i>
                <br/><span class="text">Other Inquiries</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</html>

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.SubmitCode(CodeManager.java:185)
	at com.shuzijun.leetcode.plugin.actions.SubmitAction.perform(SubmitAction.java:22)
	at com.shuzijun.leetcode.plugin.actions.AbstractAsynAction$1.run(AbstractAsynAction.java:17)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by marsprince** [comment]
看起来是503了

**Comment by zangruirui** [comment]
> 出现错误在右下角有个红色背景的叹号，里面有详细的错误日志提供一下

请求出错:

java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.shuzijun.leetcode.plugin.utils.HttpClientUtils.execute(HttpClientUtils.java:127)
	at com.shuzijun.leetcode.plugin.utils.HttpClientUtils.executePost(HttpClientUtils.java:114)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.setTestCaeAndLang(CodeManager.java:286)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.getCodeText(CodeManager.java:256)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.RuncodeCode(CodeManager.java:203)
	at com.shuzijun.leetcode.plugin.actions.RunCodeAction.perform(RunCodeAction.java:24)
	at com.shuzijun.leetcode.plugin.actions.AbstractAsynAction$1.run(AbstractAsynAction.java:17)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by wuzhongle** [comment]
run code 正常
submit error: 请求失败
但是登陆leetcode查看是Wrong Answer
最新6.1版本出现的问题，5.4还是正常的

**Comment by shuzijun** [comment]
@wuzhongle  提供一下题目号和提交的代码

**Comment by wuzhongle** [comment]
> @wuzhongle 提供一下题目号和提交的代码

[459]Repeated Substring Pattern.java
class Solution {
    public boolean repeatedSubstringPattern(String s) {
        if (s.length() <= 1) return false;
        boolean flag = true;
        for (int i = 0; i <= s.length() / 2; i++) {
            if (s.charAt(i) == s.charAt(s.length() - 1) && s.length() % (i + 1) == 0) {
                flag = true;
                for (int j = 0; j < s.length(); j++) {
                    if (s.charAt(j) != s.charAt(j % (i + 1))) {
                        flag = false;
                        break;
                    }
                }
                if (flag) return true;
            }
        }
        return false;
    }
}

**Comment by shuzijun** [comment]
@wuzhongle  安装一下这个版本[v6.2-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.2-beta)

**Comment by wuzhongle** [comment]
> @wuzhongle 安装一下这个版本[v6.2-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.2-beta)

可以了，thanks

**Comment by shuzijun** [comment]
如果有问题可以添加描述再打开这个Issues
