### ISSUE TITLE
Version 5.4 Request Error

### ISSUE THREAD

**Issue by isaaczhou** [shuzijun/leetcode-editor#82]
Upgraded to 5.4 as instructed but still get Request Error, Detailed Error see below

<img width="827" alt="Screenshot 2019-10-13 at 10 50 41 AM" src="https://user-images.githubusercontent.com/26254354/66717486-91073200-eda7-11e9-9de0-6ac3132b5937.png">

```
请求出错:

java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.shuzijun.leetcode.plugin.utils.HttpClientUtils.execute(HttpClientUtils.java:116)
	at com.shuzijun.leetcode.plugin.utils.HttpClientUtils.executeGet(HttpClientUtils.java:95)
	at com.shuzijun.leetcode.plugin.utils.HttpClientUtils.isLogin(HttpClientUtils.java:142)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.getCodeText(CodeManager.java:246)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.RuncodeCode(CodeManager.java:203)
	at com.shuzijun.leetcode.plugin.actions.RunCodeAction.perform(RunCodeAction.java:22)
	at com.shuzijun.leetcode.plugin.actions.AbstractAsynAction$1.run(AbstractAsynAction.java:17)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by shuzijun** [comment]
try this [leetcode-editor](https://github.com/shuzijun/leetcode-editor/blob/master/doc/leetcode-editor.zip)

**Comment by isaaczhou** [comment]
so far so good. Thank you.
